Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyodbc 
import pandas as pd
cnxn_str = ("Driver={odbc driver 17 for sql server};"
            "Server=DESKTOP-JAFQH21\SQLEXPRESS;"
            "Database=prosain200411100186;"
            "Trusted_Connection=yes;")
cnxn = pyodbc.connect(cnxn_str)
cursor = cnxn.cursor()	
cursor.execute("SELECT * FROM iris") 
row = cursor.fetchall() 
cursor.close()
data=[]
for i in row:
    data.append([i[0].strip('"'),i[1].strip('"'),i[2]])
df_sqlServer = pd.DataFrame(data, columns=['id','petalwidth','class'])
df_sqlServer

------------------

[0;31m[0m
[0;31mError[0mTraceback (most recent call last)
[0;32m<ipython-input-2-28d44b96bed4>[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m             [0;34m"Database=prosain200411100186;"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m             "Trusted_Connection=yes;")
[0;32m----> 7[0;31m [0mcnxn[0m [0;34m=[0m [0mpyodbc[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0mcnxn_str[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0mcursor[0m [0;34m=[0m [0mcnxn[0m[0;34m.[0m[0mcursor[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0mcursor[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0;34m"SELECT * FROM iris"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mError[0m: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'odbc driver 17 for sql server' : file not found (0) (SQLDriverConnect)")
Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'odbc driver 17 for sql server' : file not found (0) (SQLDriverConnect)")

